export const sampleProducts = [
    {
        id: 1,
        src: 'https://img.abaha.vn/photos/resized/320x/83-1600498324-myphamohui-lgvina.png',
        name: 'Đồng hồ thông minh loại 1',
        originalPrice: 550000,
        discountedPrice: 450000,
        shippingFee: 25000,
        sold: 88,
        brand: 'Whoo',
        origin: 'Hàn Quốc',
        time: '1/1/2021',
        description: 'Lorem Ipsum est un texte d’espace réservé couramment utilisé dans les industries graphique, imprimée et éditoriale pour prévisualiser les mises en page et les maquettes visuelles.',
    },
    {
        id: 2,
        src: 'https://img.abaha.vn/photos/resized/320x/83-1597318354-myphamohui-lgvina.png',
        name: 'Đồng hồ thông minh loại 2',
        originalPrice: 1250000,
        discountedPrice: 1125000,
        shippingFee: 25000,
        sold: 20,
        brand: 'MB Bank',
        origin: 'Việt Nam',
        time: '1/1/2022',
        description: 'Lorem Ipsum est un texte d’espace réservé couramment utilisé dans les industries graphique, imprimée et éditoriale pour prévisualiser les mises en page et les maquettes visuelles.',
    },
    {
        id: 3,
        src: 'https://img.abaha.vn/photos/resized/320x/83-1596624550-myphamohui-lgvina.png',
        name: 'Đồng hồ thông minh loại 3',
        originalPrice: 910000,
        discountedPrice: 819000,
        shippingFee: 25000,
        sold: 156,
        brand: 'ooo',
        origin: 'Trung Quốc',
        time: '1/1/2020',
        description: 'Lorem Ipsum est un texte d’espace réservé couramment utilisé dans les industries graphique, imprimée et éditoriale pour prévisualiser les mises en page et les maquettes visuelles.',
    },
    {
        id: 4,
        src: 'https://img.abaha.vn/photos/resized/320x/83-1596535100-myphamohui-lgvina.png',
        name: 'Đồng hồ thông minh loại 4',
        originalPrice: 1050000,
        discountedPrice: 945000,
        shippingFee: 25000,
        sold: 38,
        brand: 'pp',
        origin: 'Lào',
        time: '1/1/2024',
        description: 'Lorem Ipsum est un texte d’espace réservé couramment utilisé dans les industries graphique, imprimée et éditoriale pour prévisualiser les mises en page et les maquettes visuelles.',
    },
    {
        id: 5,
        src: 'https://img.abaha.vn/photos/resized/320x/83-1596528994-myphamohui-lgvina.png',
        name: 'Đồng hồ thông minh loại 5',
        originalPrice: 1050000,
        discountedPrice: 945000,
        shippingFee: 25000,
        sold: 88,
        brand: 'pp',
        origin: 'Lào',
        time: '1/1/2025',
        description: 'Lorem Ipsum est un texte d’espace réservé couramment utilisé dans les industries graphique, imprimée et éditoriale pour prévisualiser les mises en page et les maquettes visuelles.',
    },
    {
        id: 6,
        src: 'https://img.abaha.vn/photos/resized/320x/83-1591788607-myphamohui-lgvina.png',
        name: 'Đồng hồ thông minh loại 6',
        originalPrice: 2600000,
        discountedPrice: 2340000,
        shippingFee: 25000,
        sold: 88,
        brand: 'pp',
        origin: 'Lào',
        time: '1/10/2021',
        description: 'Lorem Ipsum est un texte d’espace réservé couramment utilisé dans les industries graphique, imprimée et éditoriale pour prévisualiser les mises en page et les maquettes visuelles.',
    },
    {
        id: 7,
        src: 'https://img.abaha.vn/photos/resized/320x/83-1591784476-myphamohui-lgvina.png',
        name: 'Đồng hồ thông minh loại 7',
        originalPrice: 3100000,
        discountedPrice: 2790000,
        shippingFee: 25000,
        sold: 88,
        brand: 'pp',
        origin: 'Lào',
        time: '1/1/2020',
        description: 'Lorem Ipsum est un texte d’espace réservé couramment utilisé dans les industries graphique, imprimée et éditoriale pour prévisualiser les mises en page et les maquettes visuelles.',
    },
    {
        id: 8,
        src: 'https://img.abaha.vn/photos/resized/320x/83-1591783524-myphamohui-lgvina.png',
        name: 'Đồng hồ thông minh loại 8',
        originalPrice: 950000,
        discountedPrice: 855000,
        shippingFee: 25000,
        sold: 100,
        brand: 'pp',
        origin: 'Lào',
        time: '1/1/2019',
        description: 'Lorem Ipsum est un texte d’espace réservé couramment utilisé dans les industries graphique, imprimée et éditoriale pour prévisualiser les mises en page et les maquettes visuelles.',
    },
    {
        id: 9,
        src: 'https://img.abaha.vn/photos/resized/320x/83-1591780389-myphamohui-lgvina.png',
        name: 'Đồng hồ thông minh loại 9',
        originalPrice: 1200000,
        discountedPrice: 1080000,
        shippingFee: 25000,
        sold: 60,
        brand: 'pp',
        origin: 'Lào',
        time: '1/1/2011',
        description: 'Lorem Ipsum est un texte d’espace réservé couramment utilisé dans les industries graphique, imprimée et éditoriale pour prévisualiser les mises en page et les maquettes visuelles.',
    },
    {
        id: 10,
        src: 'https://img.abaha.vn/photos/resized/320x/83-1591778831-myphamohui-lgvina.png',
        name: 'Đồng hồ thông minh loại 10',
        originalPrice: 2600000,
        discountedPrice: 2340000,
        shippingFee: 25000,
        sold: 88,
        brand: 'pp',
        origin: 'Lào',
        time: '1/1/2026',
        description: 'Lorem Ipsum est un texte d’espace réservé couramment utilisé dans les industries graphique, imprimée et éditoriale pour prévisualiser les mises en page et les maquettes visuelles.',
    },
    {
        id: 11,
        src: 'https://img.abaha.vn/photos/resized/320x/83-1600498324-myphamohui-lgvina.png',
        name: 'Đồng hồ thông minh loại 11',
        originalPrice: 550000,
        discountedPrice: 450000,
        shippingFee: 25000,
        sold: 88,
        brand: 'Whoo',
        origin: 'Hàn Quốc',
        time: '1/1/2021',
        description: 'Lorem Ipsum est un texte d’espace réservé couramment utilisé dans les industries graphique, imprimée et éditoriale pour prévisualiser les mises en page et les maquettes visuelles.',
    },
    {
        id: 12,
        src: 'https://img.abaha.vn/photos/resized/320x/83-1591783524-myphamohui-lgvina.png',
        name: 'Iphone loại 1',
        originalPrice: 950000,
        discountedPrice: 855000,
        shippingFee: 25000,
        sold: 100,
        brand: 'pp',
        origin: 'Lào',
        time: '1/1/2019',
        description: 'Lorem Ipsum est un texte d’espace réservé couramment utilisé dans les industries graphique, imprimée et éditoriale pour prévisualiser les mises en page et les maquettes visuelles.',
    },
    {
        id: 13,
        src: 'https://img.abaha.vn/photos/resized/320x/83-1591788607-myphamohui-lgvina.png',
        name: 'Iphone loại 2',
        originalPrice: 2600000,
        discountedPrice: 2340000,
        shippingFee: 25000,
        sold: 88,
        brand: 'pp',
        origin: 'Lào',
        time: '1/10/2021',
        description: 'Lorem Ipsum est un texte d’espace réservé couramment utilisé dans les industries graphique, imprimée et éditoriale pour prévisualiser les mises en page et les maquettes visuelles.',
    },
    {
        id: 14,
        src: 'https://img.abaha.vn/photos/resized/320x/83-1591784476-myphamohui-lgvina.png',
        name: 'Iphone loại 3',
        originalPrice: 3100000,
        discountedPrice: 2790000,
        shippingFee: 25000,
        sold: 88,
        brand: 'pp',
        origin: 'Lào',
        time: '1/1/2020',
        description: 'Lorem Ipsum est un texte d’espace réservé couramment utilisé dans les industries graphique, imprimée et éditoriale pour prévisualiser les mises en page et les maquettes visuelles.',
    },
    {
        id: 15,
        src: 'https://img.abaha.vn/photos/resized/320x/83-1600498324-myphamohui-lgvina.png',
        name: 'Iphone loại 4',
        originalPrice: 550000,
        discountedPrice: 450000,
        shippingFee: 25000,
        sold: 88,
        brand: 'Whoo',
        origin: 'Hàn Quốc',
        time: '1/1/2021',
        description: 'Lorem Ipsum est un texte d’espace réservé couramment utilisé dans les industries graphique, imprimée et éditoriale pour prévisualiser les mises en page et les maquettes visuelles.',
    },
]